package com.foreverinlove.objects

import com.foreverinlove.screen.activity.RegisterFlowStatus

data class TempUserDataObject(
    var login_otp: String = "",
    var token_type: String = "",
    var session_id: String = "",
    var token: String = "",
    var userStatus: String = "",
    var phone: String = "",
    var id: String = "",
    var first_name: String = "",
    var last_name: String = "",
    var dob: String = "",
    var age: String = "",
    var email: String = "",
    var emailVerified: String = "",
    var gender: String = "",
    var intrested: String = "",
    var job_title: String = "",
    var google_id: String = "",
    var fb_id: String = "",
    var apple_id: String = "",
    var login_type: String = "",
    var otp_expird_time: String = "",
    var address: String = "",
    var latitude: String = "",
    var longitude: String = "",
    var height: String = "",
    var about:String="",
    var is_once_purchased:Boolean=false,
    var imageUrl1: String = "",
    var imageUrl2: String = "",
    var imageUrl3: String = "",
    var imageUrl4: String = "",
    var imageUrl5: String = "",
    var imageUrl6: String = "",

    var imageId1: String = "",
    var imageId2: String = "",
    var imageId3: String = "",
    var imageId4: String = "",
    var imageId5: String = "",
    var imageId6: String = "",

    var profile_video: String = "",
    var lastseen: String = "",
    var fcm_token: String = "",

    var ukeyeducation: String = "",
    var ukeylanguage: String = "",
    var ukeypolitical_leaning: String = "",
    var ukeylooking_for: String = "",
    var ukeydietary_lifestyle: String = "",
    var ukeypets: String = "",
    var ukeyarts: String = "",
    var ukeyinterests: String = "",
    var ukeydrink: String = "",
    var ukeydrugs: String = "",
    var ukeyhoroscope: String = "",
    var ukeyreligion: String = "",
    var ukeyrelationship_status: String = "",
    var ukeylife_style: String = "",
    var ukeyfirst_date_ice_breaker: String = "",
    var ukeycovid_vaccine: String = "",
    var ukeysmoking: String = "",
    var registerFlowStatus: RegisterFlowStatus? = null,


    var sdk_token: String = "",
    var id_verification: String = "",


    )
